### ISSUE TITLE
Another noob

### ISSUE THREAD

**Issue by cavementech** [eracknaphobia/plugin.video.mlbtv#12]
Where source path do I use to install this MLB on a firestick?

**Comment by eracknaphobia** [comment]
Just install from the Official Kodi repo.
Addons > Install from repository > Kodi Repository > Video Add-ons > MLB.tv

**Comment by chovy** [comment]
@cavementech its better if you use the repo:

https://github.com/eracknaphobia/repo.eracknaphobia/blob/master/repository.eracknaphobia.zip

Download that zip, and install from zip (this installs the repo) then go into "Erackaphobia's repo" and install MLB.tv -- you will automatically get updates this way.
