### ISSUE TITLE
Unable to stream Mlb.tv after update

### ISSUE THREAD

**Issue by grandad13** [eracknaphobia/plugin.video.mlbtv#28]
Have tried logging out and back in, after faultless working for last two seasons seems unable to find any streams
Log fie https://paste.kodi.tv/tukufiyeci

**Comment by rlack0913** [comment]
Having the same issue on Kodi 18.1 (raspian stretch), mlb.tv add-on 2018.8.16.
Traced the issue to the Connection pool - line 1638 on grandad13's log file:
_InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings_

It's a relatively straight-forward fix under python 3 and slightly more complicated under python 2. I'd give this a shot but I don't have a dev environment to work with yet.

Anybody?

**Comment by eracknaphobia** [comment]
Just a warning, shouldn't stop it from playing. BTW lastest version is 2019.3.31 and is only in my repo at the moment

**Comment by rlack0913** [comment]
FYI, I went to your repo to upgrade but MLB.TV is still at 2018.8.16, the same as the Kodi Add-on repo. A couple of the others had been upgraded (NBC Sports, March Madness).

And I'm confused. I enabled debugging and tried opening some of the games. I was able to get 1 out of 3 to start. The log file is at: http://paste.kodi.tv/sokevebawe . Could this be some kind of timing issue? The ones that fail have errors like: "Playlist Player: skipping unplayable item:". I've verified that the streams are playable in a browser.

If it helps there's another log at: https://paste.kodi.tv/tasiqagame . This one had all debugging on. The relevant areas start at lines: 1680, 1783, 1826, 1977, 2139, 2226. The request for the game is at 2139 and the failure is at 2226.

Let me know if I can provide any additional info.

[kodi-tasiqagame.txt](https://github.com/eracknaphobia/plugin.video.mlbtv/files/3070053/kodi-tasiqagame.txt)
[kodi-sokevebawe.txt](https://github.com/eracknaphobia/plugin.video.mlbtv/files/3070054/kodi-sokevebawe.txt)

**Comment by tonywagner** [comment]
@rlack0913 if the repo one isn't reflecting the update, you can just download the addon (not the repo) as a zip file and install it within Kodi:

https://github.com/eracknaphobia/plugin.video.mlbtv/archive/master.zip

**Comment by rlack0913** [comment]
Thanks @tonywagner. And thank you @eracknaphobia for the plug-in. Once the update was installed it worked like a champ!

**Comment by eracknaphobia** [comment]
Good deal 👍
