### ISSUE TITLE
Radio feeds missing

### ISSUE THREAD

**Issue by tonywagner** [eracknaphobia/plugin.video.mlbtv#72]
Beginning June 25, 2024, radio feeds are no longer being published in the API used by the addon. I suspect video feeds may be affected eventually too.

So we'll eventually need to change to a new API with a whole new auth sequence. I'm debating whether to attempt this in a fork of the existing addon, or to start from scratch with a new addon designed to address https://github.com/eracknaphobia/plugin.video.mlbtv/issues/68 too. Either way, when I have something ready for testing, I will share it here!

**Comment by stephenhaberle** [comment]
This is a feature I heavily use, so I’m happy to help in any way I can to get this back.

**Comment by chrisschlitt** [comment]
Do you have any details on the new API? Noticed this broke in an app I'm working on as well but I don't know anything about what they changed to. If you have any insight I'm happy to help in any way.

**Comment by tonywagner** [comment]
Radio feeds are now available in this new project: https://github.com/tonywagner/plugin.video.mlb

**Comment by eracknaphobia** [comment]
Please try the latest version (2024.7.22+matrix.1) it should fix this issue.
