### ISSUE TITLE
MiLB Support

### ISSUE THREAD

**Issue by dephekt** [eracknaphobia/plugin.video.mlbtv#9]
What is the feasibility of extending playback support to include minor league games from milb.tv? Just wondering, if the backend functions similarly enough on both sites, if we could perhaps look forward to such support in the future or if the sites are too dramatically different that a separate plugin would really be needed instead?

**Comment by chovy** [comment]
I'm also interested in this. Eracknaphobia is the master at kodi addons for official streams.

Would love him to create one for SlingTV, PS Vue, Youtube Live and Netflix.

**Comment by eracknaphobia** [comment]
Someone has already started working on[Neflix](https://liliputing.com/2017/03/plugin-brings-netflix-to-kodi-media-center-unofficially-but-without-breaking-drm.html)

I don't have accounts for any of the other services or plan on opening accounts for them, although I've been on the fence about getting PS Vue.
